language: php

php:
  - 5.4
  - 5.5
  - hhvm
  
install:
  - composer install
  
script: phpunit -c tests/phpunit.xml tests

after_script:
  - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true